export interface MovieResponse {
    Actors: string,
    Awards: string,
    Country: string,
    Director: string,
    Genre: string,
    Language: string,
    Metascore: string,
    Plot: string,
    Poster: string,
    Rated: string,
    Released: string,
    Response: string,
    Runtime: string,
    Title: string,
    Type: string,
    Writer: string,
    Year: string,
    imdbID: string,
    imdbRating: string,
    imdbVotes: string,
    totalSeasons: string,
  }
    